apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: metrics
    isDefault: true
    editable: true
    secureJsonData:
      password: ${METRICS_DB_PASSWORD}
    jsonData:
      database: metrics
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      timeInterval: 10s
